Ts/patryk
CodersCamp2021/JoaoTeam-Project-4 pull request #3
Opened 2022-04-15 08:19 UTC by itspatys

Sorki że tak późno dopiero zacząłem coś robić ale miałem ostatnio strasznie dużo pracy różnej i było u mnie ciężko z czasem 😢

2022-04-16 06:25 UTC, spidero7 approved these changes

2022-04-16 15:56 UTC, J-emi commented on backend/routes/cinemaHall.ts
>      }
Line 45: using `mongoose` without importing that name

2022-04-16 15:57 UTC, J-emi commented on backend/routes/cinemaHall.ts
>      }
Line 61: same as 45, using `mongoose` without importing that name

2022-04-16 16:09 UTC, J-emi commented
Needs an install of `concurrently` to even start at all.

2022-04-16 16:16 UTC, J-emi requested changes

2022-04-16 16:16 UTC, J-emi commented on backend/routes/screening.ts
>      const [screeningHours, screeningMinutes] = stringToTimeTouple(movie.length)
Could you please change `String` to `string` types in `IMovie` interface so this stops throwing errors?

2022-04-16 16:16 UTC, J-emi commented on backend/routes/cinemaHall.ts
>      }
Line 61: same as 45, using `mongoose` without importing that name

2022-04-16 16:16 UTC, J-emi commented on backend/routes/cinemaHall.ts
>      }
Line 45: using `mongoose` without importing that name

2022-04-16 16:16 UTC, J-emi commented on backend/routes/screening.ts
>      return string.slice(0,-1).split("h").map(e=>(e-0))
`error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.`

2022-04-16 16:16 UTC, J-emi commented on backend/model/CinemaHall.ts
> +        type: mongoose.Types.ObjectId,
Using `mongoose` without importing that name throws an error about unrecognized name

2022-04-19 15:09 UTC, J-emi approved these changes

2022-04-19 15:31 UTC, merged